name: Deploy API Code

on:
  push:
    branches:
    - main
    
jobs:
  Test-And-Deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest

    steps:

    # Checkout from git master branch
    - name: Checkout
      uses: actions/checkout@master
    
    # Tests 
    - id: Test-code
      name: Python Tests
      run: |
        pip3 install -r requirements.txt
        python3 yason/manage.py test    
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        
    # Deploy
    - id: deploy-code
      name: Deploy Code
      run: |
        echo "use what ever deployment method you can use"
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}