name: Test API Code

on:
  pull_request:
    branches:
    - main

jobs:
  Unit-Test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:

    # Checkout from git master branch
    - name: Checkout
      uses: actions/checkout@master
    
    # Tests
    - id: Test-code
      name: Python Tests
      run: |
        pip3 install -r requirements.txt
        python3 yason/manage.py test    
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}